@startuml

object User{
firstname
lastname
}
object Hobby{
name
link
}
object HobbyInfo{
type
}
object UserInfo{
email
age
}
object Phonenumber{
phonenumber
type
}
object Zip{
zip
cityName
region
municipality
}
object Address{
streetName
number
}

Zip "1" <--> "*" Address
Address "1" <--> "1" UserInfo
Phonenumber "*" <--> "1" UserInfo
UserInfo "1" <--> "1" User
User "*" <-->  "*" Hobby
Hobby "*"<--> "*" HobbyInfo

@enduml
